version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  redis:
    image: redis:alpine